>compound EA02529522
>parentmass 395.0073
>ionization [M-H]-
>formula C12H19Cl3O8
>rt 264.000000
>profile orbitrap
#smiles_iso C([C@@H]1[C@@H]([C@@H]([C@H]([C@H](O1)O[C@]2([C@H]([C@@H]([C@H](O2)CCl)O)O)CCl)O)O)Cl)O
#smiles_can C(C1C(C(C(C(O1)OC2(C(C(C(O2)CCl)O)O)CCl)O)O)Cl)O
#inchikey BAQAVOSOZGMPRM-QBMZZYIRSA-N
#pubchem_id 71485
#mb_accession EA070351,EA070364

>ms2
359.030000 506154.400000

>ms2
359.030100 43515.300000

