>compound EA25669683
>parentmass 512.96
>ionization [M-H]-
>formula C10HF19O2
>rt 912.000000
>profile orbitrap
#smiles_iso C(=O)(C(C(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)O
#smiles_can C(=O)(C(C(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)O
#inchikey PCIUEQPBYFRTEM-UHFFFAOYSA-N
#pubchem_id 9555
#mb_accession EA272051

>ms2peaks
218.986000 59744.200000
268.982600 49106.000000
468.970300 1128824.400000

