>compound EA42210632
>parentmass 386.9644
>ionization [M-H]-
>formula C12H4Cl2F6N4
>rt 750.000000
>profile orbitrap
#smiles_iso C1=C(C=C(C(=C1Cl)N2C(=C(C(=N2)C#N)C(F)(F)F)N)Cl)C(F)(F)F
#smiles_can C1=C(C=C(C(=C1Cl)N2C(=C(C(=N2)C#N)C(F)(F)F)N)Cl)C(F)(F)F
#inchikey JWKXVHLIRTVXLD-UHFFFAOYSA-N
#pubchem_id 22673275
#mb_accession EA266951,EA266964

>ms2peaks
350.987600 131073.500000

>ms2peaks
350.987700 16058.400000

