>compound EA47548256
>parentmass 450.9263
>ionization [M-H]-
>formula C12H4Cl2F6N4O2S
>rt 810.000000
>profile orbitrap
#smiles_iso C1=C(C=C(C(=C1Cl)N2C(=C(C(=N2)C#N)S(=O)(=O)C(F)(F)F)N)Cl)C(F)(F)F
#smiles_can C1=C(C=C(C(=C1Cl)N2C(=C(C(=N2)C#N)S(=O)(=O)C(F)(F)F)N)Cl)C(F)(F)F
#inchikey LGHZJDKSVUTELU-UHFFFAOYSA-N
#pubchem_id 3078139
#mb_accession EA266751,EA266764

>ms2
414.949800 20842951.000000

>ms2
414.949600 7464736.700000

