>compound EA50553933
>parentmass 562.9568
>ionization [M-H]-
>formula C11HF21O2
>rt 978.000000
>profile orbitrap
#smiles_iso C(=O)(C(C(C(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)O
#smiles_can C(=O)(C(C(C(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)O
#inchikey SIDINRCMMRKXGQ-UHFFFAOYSA-N
#pubchem_id 77222
#mb_accession EA272251

>ms2
518.965800 458221.300000

