>compound EA59680006
>parentmass 356.0695
>ionization [M-H]-
>formula C19H16ClNO4
>rt 768.000000
>profile orbitrap
#smiles_iso CC1=C(C2=C(N1C(=O)C3=CC=C(C=C3)Cl)C=CC(=C2)OC)CC(=O)O
#smiles_can CC1=C(C2=C(N1C(=O)C3=CC=C(C=C3)Cl)C=CC(=C2)OC)CC(=O)O
#inchikey CGIGDMFJXJATDK-UHFFFAOYSA-N
#pubchem_id 3715
#mb_accession EA020751,EA020764

>ms2peaks
312.079100 331476.300000

>ms2peaks
312.079300 871886.500000

