>compound EA76730182
>parentmass 338.034
>ionization [M-H]-
>formula C14H13NO7S
>rt 372.000000
>profile orbitrap
#smiles_iso CS(=O)(=O)C1=CC(=C(C=C1)C(=O)C2C(=O)CCCC2=O)[N+](=O)[O-]
#smiles_can CS(=O)(=O)C1=CC(=C(C=C1)C(=O)C2C(=O)CCCC2=O)[N+](=O)[O-]
#inchikey KPUREKXXPHOJQT-UHFFFAOYSA-N
#pubchem_id 175967
#mb_accession EA025851,EA025864

>ms2peaks
291.033000 1141191.200000

>ms2peaks
291.032800 403968.100000

