>compound AU13283492
>parentmass 445.1997
>ionization [M+Na]+
>formula C23H31FO6
>rt 349.380000
>profile qtof
#smiles_iso CC(=O)OCC(=O)[C@]1(CC[C@@H]2[C@@]1(C[C@@H]([C@]3([C@H]2CCC4=CC(=O)CC[C@@]43C)F)O)C)O
#smiles_can CC(=O)OCC(=O)C1(CCC2C1(CC(C3(C2CCC4=CC(=O)CCC43C)F)O)C)O
#inchikey SYWHXTATXSMDSB-GSLJADNHSA-N
#pubchem_id 225609
#mb_accession AU210131

>ms2
133.085800 704.000000
177.112300 340.000000

