name: massbank2db_FILES
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.3
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - cairo=1.16.0
  - certifi=2020.12.5
  - cvxpy=1.1.10
  - cvxpy-base=1.1.10
  - cycler=0.10.0
  - cython=0.29.22
  - dbus=1.13.6
  - decorator=5.0.5
  - ecos=2.0.7.post1
  - expat=2.3.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.68.0
  - glib-tools=2.68.0
  - greenlet=1.0.0
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - icu=68.1
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - joblib=1.0.1
  - jpeg=9d
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=13.1
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - more-itertools=8.7.0
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - ncurses=6.2
  - nspr=4.30
  - nss=3.63
  - numpy=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - osqp=0.6.2
  - pandas=1.2.3
  - parso=0.8.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=21.0.1
  - pixman=0.40.0
  - prompt-toolkit=3.0.18
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycairo=1.20.0
  - pygments=2.8.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyzmq=22.0.3
  - qdldl-python=0.1.5
  - qt=5.12.9
  - rdkit=2021.03.1
  - readline=8.0
  - reportlab=3.5.66
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - scs=2.1.2
  - seaborn=0.11.1
  - setuptools=49.6.0
  - six=1.15.0
  - sqlalchemy=1.4.5
  - sqlite=3.35.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.4.9
