>compound NA04318443
>parentmass 579.1708
>ionization [M+H]+
>formula C27H30O14
>rt 551.820000
>profile orbitrap
#smiles_iso CC1[C@@H]([C@@H](C([C@@H](O1)OC2=CC(=C3C(=C2)OC(=C(C3=O)O[C@H]4[C@H](C([C@H](C(O4)C)O)O)O)C5=CC=C(C=C5)O)O)O)O)O
#smiles_can CC1C(C(C(C(O1)OC2=CC(=C3C(=C2)OC(=C(C3=O)OC4C(C(C(C(O4)C)O)O)O)C5=CC=C(C=C5)O)O)O)O)O
#inchikey PUPKKEQDLNREIM-YMCFDUETSA-N
#pubchem_id 44258935
#mb_accession NA002999,NA003000

>ms2
287.054200 1491.700000

>ms2
287.054500 1651.500000

