>compound NA77219755
>parentmass 545.2381
>ionization [M+H]+
>formula C29H36O10
>rt 565.140000
>profile orbitrap
#smiles_iso CC1=C2[C@H](C(=O)[C@@]3([C@H](C[C@@H]4[C@]([C@H]3[C@@H]([C@@](C2(C)C)(C[C@@H]1O)O)OC(=O)C5=CC=CC=C5)(CO4)OC(=O)C)O)C)O
#smiles_can CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1O)O)OC(=O)C5=CC=CC=C5)(CO4)OC(=O)C)O)C)O
#inchikey YWLXLRUDGLRYDR-ZHPRIASZSA-N
#pubchem_id 154272
#mb_accession NA002305,NA002306

>ms2peaks
522.056000 927.300000

>ms2peaks
522.059100 2108.000000

