>compound NA84603549
>parentmass 854.3382
>ionization [M+H]+
>formula C47H51NO14
>rt 740.400000
>profile orbitrap
#smiles_iso CC1=C2[C@H](C(=O)[C@@]3([C@H](C[C@@H]4[C@]([C@H]3[C@@H]([C@@](C2(C)C)(C[C@@H]1OC(=O)[C@@H]([C@H](C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)O)O)OC(=O)C7=CC=CC=C7)(CO4)OC(=O)C)O)C)OC(=O)C
#smiles_can CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)O)O)OC(=O)C7=CC=CC=C7)(CO4)OC(=O)C)O)C)OC(=O)C
#inchikey RCINICONZNJXQF-MZXODVADSA-N
#pubchem_id 36314
#mb_accession NA002484,NA002485

>ms2peaks
158.390000 2653.300000

>ms2peaks
158.390100 2185.000000

