>compound NA87181110
>parentmass 611.1607
>ionization [M+H]+
>formula C27H30O16
>rt 511.680000
>profile orbitrap
#smiles_iso CC1C(C(C(C(O1)OCC2C(C(C(C(O2)OC3=C(OC4=CC(=CC(=C4C3=O)O)O)C5=CC(=C(C=C5)O)O)O)O)O)O)O)O
#smiles_can CC1C(C(C(C(O1)OCC2C(C(C(C(O2)OC3=C(OC4=CC(=CC(=C4C3=O)O)O)C5=CC(=C(C=C5)O)O)O)O)O)O)O)O
#inchikey IKGXIBQEEMLURG-UHFFFAOYSA-N
#pubchem_id 5293655
#mb_accession NA002616,NA002617

>ms2peaks
303.049700 2039.200000

>ms2peaks
303.049400 2352.700000

