>compound AU48644988
>parentmass 526.9615
>ionization [M-H]-
>formula C10H5F17O3S
>rt 666.700000
>profile qtof
#smiles_iso C(CS(=O)(=O)O)C(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F
#smiles_can C(CS(=O)(=O)O)C(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F
#inchikey ALVYVCQIFHTIRD-UHFFFAOYSA-N
#pubchem_id 3016044
#mb_accession AU594350,AU594351,AU594352

>ms2peaks
526.961400 796.000000

>ms2peaks
526.961900 764.000000

>ms2peaks
526.960700 392.000000

