>compound AU71076915
>parentmass 784.3451
>ionization [M-H]-
>formula C43H51N3O11
>rt 598.110000
>profile qtof
#smiles_iso C[C@H]1/C=C/C=C(\C(=O)NC2=C(C3=C(C4=C(C(=C3O)C)O[C@@](C4=O)(O/C=C/[C@@H]([C@H]([C@H]([C@@H]([C@@H]([C@@H]([C@H]1O)C)O)C)OC(=O)C)C)OC)C)C5=C2N6C=CC(=CC6=N5)C)O)/C
#smiles_can CC1C=CC=C(C(=O)NC2=C(C3=C(C4=C(C(=C3O)C)OC(C4=O)(OC=CC(C(C(C(C(C(C1O)C)O)C)OC(=O)C)C)OC)C)C5=C2N6C=CC(=CC6=N5)C)O)C
#inchikey NZCRJKRKKOLAOJ-XRCRFVBUSA-N
#pubchem_id 6436173
#mb_accession AU117952,AU117953

>ms2
784.337500 672.000000

>ms2
784.337600 520.000000

