>compound BS21853941
>parentmass 562.313
>ionization [M+HCOO]-
>formula C26H48NO7P
>rt 1293.600000
>profile qtof
#smiles_iso CC/C=C\C/C=C\C/C=C\CCCCCCCC(=O)OC[C@H](COP(=O)([O-])OCC[N+](C)(C)C)O
#smiles_can CCC=CCC=CCC=CCCCCCCCC(=O)OCC(COP(=O)([O-])OCC[N+](C)(C)C)O
#inchikey WKQNRCYKYCKESD-YVHLTTHBSA-N
#pubchem_id 24779469
#mb_accession BS001063

>ms2peaks
224.068000 96.000000
277.216000 999.000000
278.220000 225.000000

