>compound BS49945490
>parentmass 795.4482
>ionization [M-H]-
>formula C42H68O14
>rt 1060.800000
>profile qtof
#smiles_iso C[C@@]12CC[C@@]3(C(=CCC4[C@]3(CCC5[C@@]4(CC[C@@H]([C@]5(C)CO)O[C@H]6[C@@H]([C@H]([C@@H]([C@H](O6)C(=O)O)O)O)O[C@H]7[C@@H]([C@H]([C@H]([C@H](O7)CO)O)O)O)C)C)[C@@H]1CC(C[C@H]2O)(C)C)C
#smiles_can CC1(CC2C3=CCC4C5(CCC(C(C5CCC4(C3(CCC2(C(C1)O)C)C)C)(C)CO)OC6C(C(C(C(O6)C(=O)O)O)O)OC7C(C(C(C(O7)CO)O)O)O)C)C
#inchikey OKIHRVKXRCAJFQ-VAJUJSSWSA-N
#pubchem_id 134755458
#mb_accession BS001122

>ms2
795.452900 999.000000
796.456400 428.000000
797.459400 45.000000

