>compound BS54599186
>parentmass 795.4572
>ionization [M-H]-
>formula C42H68O14
>rt 1078.200000
>profile qtof
#smiles_iso C[C@@]12CC[C@@]3(C(=CCC4[C@]3(CCC5[C@@]4(CC[C@@H]([C@]5(C)CO)O[C@H]6[C@@H]([C@H]([C@@H]([C@H](O6)C(=O)O)O)O)O[C@H]7[C@@H]([C@H]([C@@H]([C@H](O7)CO)O)O)O)C)C)[C@@H]1CC(C[C@H]2O)(C)C)C
#smiles_can CC1(CC2C3=CCC4C5(CCC(C(C5CCC4(C3(CCC2(C(C1)O)C)C)C)(C)CO)OC6C(C(C(C(O6)C(=O)O)O)O)OC7C(C(C(C(O7)CO)O)O)O)C)C
#inchikey OKIHRVKXRCAJFQ-OFOMSTTESA-N
#pubchem_id 134755457
#mb_accession BS001123

>ms2
795.457200 999.000000
796.459500 440.000000
797.460700 95.000000

