>compound BS59767177
>parentmass 562.313
>ionization [M+HCOO]-
>formula C26H48NO7P
>rt 1257.600000
>profile qtof
#smiles_iso CC/C=C\C/C=C\C/C=C\CCCCCCCC(=O)O[C@H](CO)COP(=O)([O-])OCC[N+](C)(C)C
#smiles_can CCC=CCC=CCC=CCCCCCCCC(=O)OC(CO)COP(=O)([O-])OCC[N+](C)(C)C
#inchikey WVUARHUSWJUGTE-YVHLTTHBSA-N
#pubchem_id 134777355
#mb_accession BS001060

>ms2peaks
277.217000 999.000000
278.221000 220.000000

