>compound BS64299686
>parentmass 811.4452
>ionization [M+HCOO]-
>formula C41H66O13
>rt 926.400000
>profile qtof
#smiles_iso C[C@]12CC[C@@H]([C@@](C1CC[C@@]3(C2CC=C4[C@]3(CC[C@@]5([C@H]4CC(CC5)(C)C)C(=O)O[C@H]6[C@@H]([C@H]([C@@H]([C@H](O6)CO)O)O)O)C)C)(C)CO)O[C@H]7[C@@H]([C@H]([C@H](CO7)O)O)O
#smiles_can CC1(CCC2(CCC3(C(=CCC4C3(CCC5C4(CCC(C5(C)CO)OC6C(C(C(CO6)O)O)O)C)C)C2C1)C)C(=O)OC7C(C(C(C(O7)CO)O)O)O)C
#inchikey UCVNVSOIAFGLPL-FBTWDWMFSA-N
#pubchem_id 134769728
#mb_accession BS001154

>ms2peaks
603.390700 999.000000
604.394000 327.000000
605.396300 50.000000

