>compound EA11163510
>parentmass 569.9673
>ionization [M-H]-
>formula C11H6F17NO4S
>rt 990.000000
>profile orbitrap
#smiles_iso CN(CC(=O)O)S(=O)(=O)C(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F
#smiles_can CN(CC(=O)O)S(=O)(=O)C(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F
#inchikey QNDHIRFIMVNHBN-UHFFFAOYSA-N
#pubchem_id 22286931
#mb_accession EA292053

>ms2peaks
168.989200 7131.500000
218.986200 10860.500000

