>compound EA23713173
>parentmass 386.9644
>ionization [M-H]-
>formula C12H4Cl2F6N4
>rt 750.000000
>profile orbitrap
#smiles_iso C1=C(C=C(C(=C1Cl)N2C(=C(C(=N2)C#N)C(F)(F)F)N)Cl)C(F)(F)F
#smiles_can C1=C(C=C(C(=C1Cl)N2C(=C(C(=N2)C#N)C(F)(F)F)N)Cl)C(F)(F)F
#inchikey JWKXVHLIRTVXLD-UHFFFAOYSA-N
#pubchem_id 22673275
#mb_accession EA266952,EA266953

>ms2
350.987100 5978.300000

>ms2
350.987300 3470.300000

