>compound EA46560409
>parentmass 456.9727
>ionization [M-H]-
>formula C10H2F16O2
>rt 966.000000
>profile orbitrap
#smiles_iso C(=C(/C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)\F)\C(=O)O
#smiles_can C(=C(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)F)C(=O)O
#inchikey WHZXTVOEGZRRJM-UPHRSURJSA-N
#pubchem_id 11733192
#mb_accession EA273353,EA273359

>ms2peaks
392.976400 10996.400000

>ms2peaks
392.976000 2711.700000

