>compound UT79393219
>parentmass 876.58
>ionization [M+CH3COO]-
>formula C47H80NO8P
>rt 795.000000
>profile orbitrap
#smiles_iso CCCCCCCCCCCC/C=C\CCC(=O)OCC(COP(=O)([O-])OCC[N+](C)(C)C)OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC
#smiles_can CCCCCCCCCCCCC=CCCC(=O)OCC(COP(=O)([O-])OCC[N+](C)(C)C)OC(=O)CCC=CCC=CCC=CCC=CCC=CCC=CCC
#inchikey ZOGZAROTKOYYRM-OOCWWCMUSA-N
#pubchem_id 134784900
#mb_accession UT001773

>ms2
802.260000 111.400000

