>compound RP38956147
>parentmass 503.1618
>ionization [M-H]-
>formula C18H32O16
>rt 36.180000
>profile qtof
#smiles_iso C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@H]2[C@@H]([C@H](O[C@@]2(CO)O[C@@H]3[C@@H]([C@H]([C@@H]([C@H](O3)CO)O)O)O)CO)O)O)O)O)O
#smiles_can C(C1C(C(C(C(O1)OC2C(C(OC2(CO)OC3C(C(C(C(O3)CO)O)O)O)CO)O)O)O)O)O
#inchikey QWIZNVHXZXRPDR-WSCXOGSTSA-N
#pubchem_id 92817
#mb_accession RP023111

>ms2peaks
411.941700 28.000000
503.162700 140.000000

