>compound EA92585354
>parentmass 336.1166
>ionization [M+H]+
>formula C13H16F3N3O4
>rt 990.000000
>profile orbitrap
#smiles_iso CCCN(CCC)C1=C(C=C(C=C1[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]
#smiles_can CCCN(CCC)C1=C(C=C(C=C1[N+](=O)[O-])C(F)(F)F)[N+](=O)[O-]
#inchikey ZSDSQXJSNMTJDA-UHFFFAOYSA-N
#pubchem_id 5569
#mb_accession EA012302,EA012308

>ms2peaks
336.117000 3084.300000

>ms2peaks
336.117000 2635.600000

