>compound EA16798177
>parentmass 790.9896
>ionization [M+H]+
>formula C16H9F26O4P
>rt 1086.000000
>profile orbitrap
#smiles_iso C(COP(=O)(O)OCCC(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F
#smiles_can C(COP(=O)(O)OCCC(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F
#inchikey ZDYYWMSLMLTXDM-UHFFFAOYSA-N
#pubchem_id 14550408
#mb_accession EA292201,EA292214

>ms2
444.985200 105409.300000

>ms2
444.985300 56839.500000

