>compound EA26305384
>parentmass 436.946
>ionization [M+H]+
>formula C12H4Cl2F6N4OS
>rt 756.000000
>profile orbitrap
#smiles_iso C1=C(C=C(C(=C1Cl)N2C(=C(C(=N2)C#N)S(=O)C(F)(F)F)N)Cl)C(F)(F)F
#smiles_can C1=C(C=C(C(=C1Cl)N2C(=C(C(=N2)C#N)S(=O)C(F)(F)F)N)Cl)C(F)(F)F
#inchikey ZOCSXAVNDGMNBV-UHFFFAOYSA-N
#pubchem_id 3352
#mb_accession EA266601,EA266614

>ms2
367.950200 380465.500000

>ms2
367.949900 93316.900000

