>compound EA34585682
>parentmass 990.9768
>ionization [M+H]+
>formula C20H9F34O4P
>rt 1224.000000
>profile orbitrap
#smiles_iso C(COP(=O)(O)OCCC(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)C(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F
#smiles_can C(COP(=O)(O)OCCC(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)C(C(C(C(C(C(C(C(F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F)(F)F
#inchikey AFWOYEYXUDHGHF-UHFFFAOYSA-N
#pubchem_id 3022253
#mb_accession EA292301,EA292314

>ms2
544.978100 65608.600000

>ms2
325.958400 1676.900000
544.978700 47510.200000

