>compound EA49585897
>parentmass 837.5318
>ionization [M+H]+
>formula C41H76N2O15
>rt 606.000000
>profile orbitrap
#smiles_iso CC[C@@H]1[C@@]([C@@H]([C@H](/C(=N/OCOCCOC)/[C@@H](C[C@@]([C@@H]([C@H]([C@@H]([C@H](C(=O)O1)C)O[C@H]2C[C@@]([C@H]([C@@H](O2)C)O)(C)OC)C)O[C@H]3[C@@H]([C@H](C[C@H](O3)C)N(C)C)O)(C)O)C)C)O)(C)O
#smiles_can CCC1C(C(C(C(=NOCOCCOC)C(CC(C(C(C(C(C(=O)O1)C)OC2CC(C(C(O2)C)O)(C)OC)C)OC3C(C(CC(O3)C)N(C)C)O)(C)O)C)C)O)(C)O
#inchikey RXZBMPWDPOLZGW-XMRMVWPWSA-N
#pubchem_id 6915744
#mb_accession EA019201,EA019214

>ms2peaks
430.266700 5287.100000
661.427200 17138.000000
679.437100 616419.800000

>ms2peaks
661.429100 1337.400000
679.436600 127945.600000

