>compound EA68438655
>parentmass 916.5264
>ionization [M+H]+
>formula C46H77NO17
>rt 486.000000
>profile orbitrap
#smiles_iso CC[C@@H]1[C@H](/C=C(/C=C/C(=O)[C@@H](C[C@@H]([C@@H]([C@H]([C@@H](CC(=O)O1)O)C)O[C@H]2[C@@H]([C@H]([C@@H]([C@H](O2)C)O[C@H]3C[C@@]([C@H]([C@@H](O3)C)O)(C)O)N(C)C)O)CC=O)C)\C)CO[C@H]4[C@@H]([C@@H]([C@@H]([C@H](O4)C)O)OC)OC
#smiles_can CCC1C(C=C(C=CC(=O)C(CC(C(C(C(CC(=O)O1)O)C)OC2C(C(C(C(O2)C)OC3CC(C(C(O3)C)O)(C)O)N(C)C)O)CC=O)C)C)COC4C(C(C(C(O4)C)O)OC)OC
#inchikey WBPYTXDJUQJLPQ-VMXQISHHSA-N
#pubchem_id 5280440
#mb_accession EA018701,EA018714

>ms2
754.435500 17270.700000
772.447600 451856.600000

>ms2
549.561200 1725.500000
754.434800 3618.200000
772.447300 77418.400000

