>compound BML1570353
>parentmass 640.2766
>ionization [M+H]+
>formula C35H37N5O7
>rt 602.280000
>profile qtof
#smiles_iso CC(C)C(=O)NC1=NC2=C(C(=O)N1)N=CN2[C@H]3C[C@@H]([C@H](O3)COC(C4=CC=CC=C4)(C5=CC=C(C=C5)OC)C6=CC=C(C=C6)OC)O
#smiles_can CC(C)C(=O)NC1=NC2=C(C(=O)N1)N=CN2C3CC(C(O3)COC(C4=CC=CC=C4)(C5=CC=C(C=C5)OC)C6=CC=C(C=C6)OC)O
#inchikey RMQXDNUKLIDXOS-ZGIBFIJWSA-N
#pubchem_id 135445746
#mb_accession BML01760

>ms2
303.136500 217.000000

