>compound BML2401196
>parentmass 471.3469
>ionization [M+H]+
>formula C30H46O4
>rt 700.680000
>profile qtof
#smiles_iso CC1(C2CCC3(C(C2(CCC1O)C)C(=O)C=C4C3(CCC5(C4CC(CC5)(C)C(=O)O)C)C)C)C
#smiles_can CC1(C2CCC3(C(C2(CCC1O)C)C(=O)C=C4C3(CCC5(C4CC(CC5)(C)C(=O)O)C)C)C)C
#inchikey MPDGHEJMBKOTSU-UHFFFAOYSA-N
#pubchem_id 3230
#mb_accession BML00475,BML00484

>ms2peaks
471.346000 488.000000

>ms2peaks
471.344300 271.000000

