>compound BML6579627
>parentmass 511.3394
>ionization [M+Na]+
>formula C30H48O5
>rt 608.580000
>profile qtof
#smiles_iso C[C@@H]1CC[C@@]2(CC[C@@]3(C(=CC[C@H]4[C@]3(CC[C@@H]5[C@@]4(C[C@H]([C@@H]([C@@]5(C)CO)O)O)C)C)[C@@H]2[C@H]1C)C)C(=O)O
#smiles_can CC1CCC2(CCC3(C(=CCC4C3(CCC5C4(CC(C(C5(C)CO)O)O)C)C)C2C1C)C)C(=O)O
#inchikey JXSVIVRDWWRQRT-UYDOISQJSA-N
#pubchem_id 119034
#mb_accession BML00703,BML00712

>ms2peaks
511.329900 236.000000

>ms2peaks
511.330300 140.000000

