>compound UF43290277
>parentmass 407.221
>ionization [M+H]+
>formula C18H34N2O6S
>rt 809.280000
>profile orbitrap
#smiles_iso CCC[C@@H]1C[C@H](N(C1)C)C(=O)N[C@@H]([C@@H]2[C@@H]([C@@H]([C@H]([C@H](O2)SC)O)O)O)[C@@H](C)O
#smiles_can CCCC1CC(N(C1)C)C(=O)NC(C2C(C(C(C(O2)SC)O)O)O)C(C)O
#inchikey OJMMVQQUTAEWLP-KIDUDLJLSA-N
#pubchem_id 3000540
#mb_accession UF410501,UF410502

>ms2peaks
126.127700 786754.800000

>ms2peaks
126.127800 679508.900000

